### ISSUE TITLE
[Enhancement] Allow customizing announcement channel

### ISSUE THREAD

**Issue by warcraftchase** [valkyrnstudios/TankBuddy#12]
Can you make a feature where while you have assist the taunt resisted doesnt do a raid warning, that part is really annoying. im the main tank and the loot master, so its very annoying to have the /raid warning going off randomly and sometimes 3 times (since im a pally)  i love the /yell part, so would want a feature to set it to only /yell. 

Other than this, the addon is amazing for tanks and i legit love it

Also a feature for ironshield potions and stuff like that

**Comment by SabreValkyrn** [comment]
>Also a feature for ironshield potions and stuff like that

This is possible as of v3.0.8 and custom item support, add the buff and duration to the menu options and it'll announce for you.

**Comment by SabreValkyrn** [comment]
>doesnt do a raid warning,

Going to close this out, no longer raid warnings as of v3.0.10. Custom channel support is harder because of API restrictions.
