### ISSUE TITLE
Localization for EU EN

### ISSUE THREAD

**Issue by Nanik263** [valkyrnstudios/TankBuddy#6]
As it seems, there is currently no localization for EU en clients. Would be great if you could add this.

**Comment by SabreValkyrn** [comment]
Could you post the explicit error?

"EU en" should be `enGB` locale, which if I'm reading this right will automatically load `enUS` https://github.com/valkyrnstudios/TankBuddy/blob/a24842a0d357f11498777e352637b7f739ad9a32/libs/AceLocale-3.0/AceLocale-3.0.lua#L20-L22

**Comment by Nanik263** [comment]
![WoWScrnShot_061121_072226 (2)](https://user-images.githubusercontent.com/85681631/121635042-e23c5d00-ca85-11eb-926d-5baf2c86a089.jpg)

This is the Error I get.

**Comment by SabreValkyrn** [comment]
That is completely different than locale support.

Should be fixed in v3.0.3, cad03bf7e205f69ba69dd3f27ac45c0ec84b18de
