### ISSUE TITLE
Unrecognized abilityName: Growl

### ISSUE THREAD

**Issue by Nanik263** [valkyrnstudios/TankBuddy#7]
Same issue as with Challenging Roar applies to Growl. :)

**Comment by SabreValkyrn** [comment]
Thanks, sorry about that. My Druid and Paladin are only level 1 so can't test them very well.

Fixed in 3.0.4, d2e4ccc10d8ee0d01d1e82844c711e242d97a705

**Comment by Nanik263** [comment]
No problem. If you need to test anything for druid, just let me know. Im glad if I can help. :)
